//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.21 at 04:11:28 PM CET 
//


package com.beetlekhi.grafcet.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parsing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Action_QNAME = new QName("", "action");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parsing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequiredSteps }
     * 
     */
    public RequiredSteps createRequiredSteps() {
        return new RequiredSteps();
    }

    /**
     * Create an instance of {@link Required }
     * 
     */
    public Required createRequired() {
        return new Required();
    }

    /**
     * Create an instance of {@link Grafcet }
     * 
     */
    public Grafcet createGrafcet() {
        return new Grafcet();
    }

    /**
     * Create an instance of {@link Steps }
     * 
     */
    public Steps createSteps() {
        return new Steps();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Transitions }
     * 
     */
    public Transitions createTransitions() {
        return new Transitions();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link ExecutedSteps }
     * 
     */
    public ExecutedSteps createExecutedSteps() {
        return new ExecutedSteps();
    }

    /**
     * Create an instance of {@link Executed }
     * 
     */
    public Executed createExecuted() {
        return new Executed();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

}
