//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.21 at 04:11:28 PM CET 
//


package com.beetlekhi.grafcet.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}required-steps" minOccurs="0"/>
 *         &lt;element ref="{}executed-steps" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requiredSteps",
    "executedSteps"
})
@XmlRootElement(name = "transition")
public class Transition {

    @XmlElement(name = "required-steps")
    protected RequiredSteps requiredSteps;
    @XmlElement(name = "executed-steps")
    protected ExecutedSteps executedSteps;
    @XmlAttribute(name = "num")
    protected Integer num;
    @XmlAttribute(name = "x")
    protected Integer x;
    @XmlAttribute(name = "y")
    protected Integer y;

    /**
     * Gets the value of the requiredSteps property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredSteps }
     *     
     */
    public RequiredSteps getRequiredSteps() {
        return requiredSteps;
    }

    /**
     * Sets the value of the requiredSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredSteps }
     *     
     */
    public void setRequiredSteps(RequiredSteps value) {
        this.requiredSteps = value;
    }

    /**
     * Gets the value of the executedSteps property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutedSteps }
     *     
     */
    public ExecutedSteps getExecutedSteps() {
        return executedSteps;
    }

    /**
     * Sets the value of the executedSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutedSteps }
     *     
     */
    public void setExecutedSteps(ExecutedSteps value) {
        this.executedSteps = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNum(Integer value) {
        this.num = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setX(Integer value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setY(Integer value) {
        this.y = value;
    }

}
